# Generated by Django 5.0.1 on 2024-02-26 18:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('first', models.CharField(max_length=32)),
                ('last', models.CharField(max_length=32)),
                ('current', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
                ('private_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('filters', models.CharField(blank=True, default='', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('matched', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank', 'Bank'), ('Expected', 'Expected')], max_length=8, null=True)),
                ('Resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resident')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(blank=True, null=True, upload_to='Invoices/')),
                ('invoice_number', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('obsolete', models.BooleanField(blank=True, default=False, null=True)),
                ('matched', models.BooleanField(blank=True, default=False, null=True)),
                ('Payment', models.ManyToManyField(blank=True, to='main.payment')),
                ('Resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resident')),
            ],
        ),
    ]
