# Generated by Django 5.0.1 on 2024-02-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
