# Generated by Django 5.0.1 on 2024-02-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_invoice_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
