# Generated by Django 5.0.1 on 2024-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_invoice_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='sefton_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Santander', 'Santander'), ('RBS', 'RBS')], max_length=9, null=True),
        ),
    ]
