# Generated by Django 5.0.1 on 2024-04-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sefton_password_alter_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='sefton_login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('passcode', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='sefton_password',
        ),
    ]
