# Generated by Django 5.0.1 on 2024-04-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sefton_login_details_delete_sefton_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='sefton_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
