# Generated by Django 5.0.1 on 2024-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_resident_leave_date_resident_sefton_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='customer_ref_no',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
