# Generated by Django 5.0.1 on 2024-05-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resident_customer_ref_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='leave_date',
        ),
    ]
