# Generated by Django 5.0.1 on 2024-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_resident_leave_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={'ordering': ['start_date']},
        ),
        migrations.AddField(
            model_name='resident',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
