# Generated by Django 5.0.1 on 2024-05-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_resident_options_resident_leave_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resident',
            options={},
        ),
    ]
