# Generated by Django 5.0.1 on 2024-05-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_resident_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='sefton_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('Resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.resident')),
            ],
        ),
    ]
