# Generated by Django 5.0.1 on 2026-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sefton_action_item_last_post_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='matched',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='matched',
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Santander', 'Santander'), ('RBS', 'RBS')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
